# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ceasar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(818, 658)
        self.btn_encrypt = QtWidgets.QPushButton(Form)
        self.btn_encrypt.setGeometry(QtCore.QRect(270, 510, 101, 31))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(Form)
        self.btn_decrypt.setGeometry(QtCore.QRect(480, 520, 101, 31))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 90, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 270, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 340, 81, 21))
        self.label_3.setObjectName("label_3")
        self.txt_plain_text = QtWidgets.QTextEdit(Form)
        self.txt_plain_text.setGeometry(QtCore.QRect(170, 90, 401, 131))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_key = QtWidgets.QTextEdit(Form)
        self.txt_key.setGeometry(QtCore.QRect(170, 270, 401, 31))
        self.txt_key.setObjectName("txt_key")
        self.txt_cipher_text = QtWidgets.QTextEdit(Form)
        self.txt_cipher_text.setGeometry(QtCore.QRect(170, 340, 411, 131))
        self.txt_cipher_text.setObjectName("txt_cipher_text")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_encrypt.setText(_translate("Form", "Encrypt"))
        self.btn_decrypt.setText(_translate("Form", "Decrypt"))
        self.label.setText(_translate("Form", "Plain_text"))
        self.label_2.setText(_translate("Form", "Key"))
        self.label_3.setText(_translate("Form", "Cipher_Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
